### ISSUE TITLE
Upstream documentation should not mention CloudForms

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-nuage-docs#1]
Upstream documentation should not mention CloudForms.  It can be done in a switchable way, where multiple targets exist, but if this is under the ManageIQ umbrella it should speak in terms of ManageIQ.

cc @adahms

**Comment by pdellaert** [comment]
Closed, thanks for the feedback and the suggestion, i've updated it using the proper variables according to the ManageIQ doc info
